"""Session recovery

Revision ID: 155b518ebeb5
Revises: 5ae8f9f63cf5
Create Date: 2025-11-27 17:52:56.629639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155b518ebeb5'
down_revision = '5ae8f9f63cf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('phone_suffix', sa.String(length=4), nullable=False),
    sa.Column('attempt_time', sa.DateTime(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_attempt_attempt_time'), ['attempt_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_attempt_ip_address'), ['ip_address'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_attempt_ip_address'))
        batch_op.drop_index(batch_op.f('ix_access_attempt_attempt_time'))

    op.drop_table('access_attempt')
    # ### end Alembic commands ###
