"""Add status and sse_channel_id to Purchase model

Revision ID: 34e9bb1aa9ee
Revises: 3b2b07b9cb1b
Create Date: 2025-11-17 13:36:32.044393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e9bb1aa9ee'
down_revision = '3b2b07b9cb1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sse_channel_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_purchase_sse_channel_id'), ['sse_channel_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_sse_channel_id'))
        batch_op.drop_column('sse_channel_id')

    # ### end Alembic commands ###
