"""Add status and sse_channel_id to Purchase model

Revision ID: 3b2b07b9cb1b
Revises: 26243d285767
Create Date: 2025-11-17 13:28:16.778564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b2b07b9cb1b'
down_revision = '26243d285767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='purchasestatus'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
