"""add allow_download

Revision ID: 6242fa5c4b84
Revises: 155b518ebeb5
Create Date: 2025-12-22 08:23:12.978606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6242fa5c4b84'
down_revision = '155b518ebeb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('digital_asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_download', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('digital_asset', schema=None) as batch_op:
        batch_op.drop_column('allow_download')

    # ### end Alembic commands ###
