"""sms_ip_tracking_recurring_campaigns_global_sms_log

Revision ID: 7497bf398617
Revises: bd6dfc8bc7e7
Create Date: 2026-04-17 11:46:58.122481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7497bf398617'
down_revision = 'bd6dfc8bc7e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=25), nullable=False),
    sa.Column('message_preview', sa.String(length=200), nullable=True),
    sa.Column('log_type', sa.Enum('PURCHASE', 'MAGIC_LINK', 'REMINDER', 'CAMPAIGN', name='smslogtype'), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['sms_campaign.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_log_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_log_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_log_sent_at'), ['sent_at'], unique=False)

    with op.batch_alter_table('sms_campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recurrence_interval_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('next_run_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('smart_exclude_recent_buyers', sa.Boolean(), nullable=True))

    with op.batch_alter_table('sms_magic_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_magic_link', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    with op.batch_alter_table('sms_campaign', schema=None) as batch_op:
        batch_op.drop_column('smart_exclude_recent_buyers')
        batch_op.drop_column('next_run_at')
        batch_op.drop_column('recurrence_interval_days')
        batch_op.drop_column('is_recurring')

    with op.batch_alter_table('sms_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_log_sent_at'))
        batch_op.drop_index(batch_op.f('ix_sms_log_creator_id'))
        batch_op.drop_index(batch_op.f('ix_sms_log_campaign_id'))

    op.drop_table('sms_log')
    # ### end Alembic commands ###
