"""asset display_order and is_pinned

Revision ID: 9e285ad86707
Revises: a4ec3003b961
Create Date: 2026-06-24 15:07:16.738929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e285ad86707'
down_revision = 'a4ec3003b961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('digital_asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('is_pinned', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('digital_asset', schema=None) as batch_op:
        batch_op.drop_column('is_pinned')
        batch_op.drop_column('display_order')

    # ### end Alembic commands ###
