"""purchase_referral_attribution_columns

Revision ID: a4ec3003b961
Revises: 7497bf398617
Create Date: 2026-04-21 21:08:28.038554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4ec3003b961'
down_revision = '7497bf398617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visitor_refcode', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('visitor_source', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('refcode_used', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('source_used', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('refcode_outcome', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_purchase_refcode_used'), ['refcode_used'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_visitor_refcode'), ['visitor_refcode'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_visitor_refcode'))
        batch_op.drop_index(batch_op.f('ix_purchase_refcode_used'))
        batch_op.drop_column('refcode_outcome')
        batch_op.drop_column('source_used')
        batch_op.drop_column('refcode_used')
        batch_op.drop_column('visitor_source')
        batch_op.drop_column('visitor_refcode')

    # ### end Alembic commands ###
