"""add asset position

Revision ID: a6313ed77c11
Revises: 6242fa5c4b84
Create Date: 2026-02-01 01:14:57.612710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6313ed77c11'
down_revision = '6242fa5c4b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))
        batch_op.drop_column('order_index')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.INTEGER(), nullable=True))
        batch_op.drop_column('position')

    # ### end Alembic commands ###
