"""add_sms_magic_link_campaigns_subscription_tiers

Revision ID: bd6dfc8bc7e7
Revises: c7d2e3f4a5b6
Create Date: 2026-04-15 10:07:52.795625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd6dfc8bc7e7'
down_revision = 'c7d2e3f4a5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'SENDING', 'SENT', 'FAILED', name='smscampaignstatus'), nullable=False),
    sa.Column('targeting', sa.JSON(), nullable=False),
    sa.Column('total_recipients', sa.Integer(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_campaign', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_campaign_creator_id'), ['creator_id'], unique=False)

    op.create_table('sms_campaign_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=25), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['sms_campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_campaign_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_campaign_log_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('sms_magic_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=25), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('opens_remaining', sa.Integer(), nullable=True),
    sa.Column('sms_count', sa.Integer(), nullable=True),
    sa.Column('last_sms_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['digital_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_magic_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_magic_link_phone_number'), ['phone_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_magic_link_token'), ['token'], unique=True)

    with op.batch_alter_table('digital_asset', schema=None) as batch_op:
        batch_op.alter_column('subscription_interval',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY', 'HALFYEARLY', 'YEARLY', name='subscriptioninterval'),
               existing_nullable=True)

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('interval',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY', 'HALFYEARLY', 'YEARLY', name='subscriptioninterval'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('interval',
               existing_type=sa.Enum('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY', 'HALFYEARLY', 'YEARLY', name='subscriptioninterval'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    with op.batch_alter_table('digital_asset', schema=None) as batch_op:
        batch_op.alter_column('subscription_interval',
               existing_type=sa.Enum('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY', 'HALFYEARLY', 'YEARLY', name='subscriptioninterval'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)

    with op.batch_alter_table('sms_magic_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_magic_link_token'))
        batch_op.drop_index(batch_op.f('ix_sms_magic_link_phone_number'))

    op.drop_table('sms_magic_link')
    with op.batch_alter_table('sms_campaign_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_campaign_log_campaign_id'))

    op.drop_table('sms_campaign_log')
    with op.batch_alter_table('sms_campaign', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_campaign_creator_id'))

    op.drop_table('sms_campaign')
    # ### end Alembic commands ###
