"""

Revision ID: ce9962b9edbe
Revises: d9a6c6a98f1f
Create Date: 2025-11-26 05:53:12.546174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce9962b9edbe'
down_revision = 'd9a6c6a98f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_file', schema=None) as batch_op:
        batch_op.drop_column('is_downloadable')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_downloadable', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
