"""Initial complete database schema

Revision ID: d9a6c6a98f1f
Revises: 
Create Date: 2025-11-26 03:45:23.994658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a6c6a98f1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_downloadable', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_file', schema=None) as batch_op:
        batch_op.drop_column('is_downloadable')

    # ### end Alembic commands ###
