"""Initial complete database schema

Revision ID: da279646049d
Revises: 
Create Date: 2025-10-27 09:52:50.083169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da279646049d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('totp_secret', sa.String(length=32), nullable=False),
    sa.Column('store_name', sa.String(length=120), nullable=True),
    sa.Column('currency_symbol', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=25), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_whatsapp_number'), ['whatsapp_number'], unique=True)

    op.create_table('ambassador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('affiliate_code', sa.String(length=50), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    with op.batch_alter_table('ambassador', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ambassador_affiliate_code'), ['affiliate_code'], unique=True)

    op.create_table('digital_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=512), nullable=True),
    sa.Column('asset_type', sa.Enum('DIGITAL_PRODUCT', 'VIDEO_SERIES', 'AUDIO_ALBUM', 'EBOOK', 'PHOTO_PACK', 'TEMPLATE', 'TICKET', name='assettype'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['digital_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('digital_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_digital_asset_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_digital_asset_slug'), ['slug'], unique=True)

    op.create_table('asset_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['digital_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['digital_asset.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_token', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('payment_gateway_ref', sa.String(length=255), nullable=True),
    sa.Column('ticket_status', sa.Enum('VALID', 'USED', 'EXPIRED', name='ticketstatus'), nullable=True),
    sa.Column('ticket_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['digital_asset.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_transaction_token'), ['transaction_token'], unique=True)

    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELED', 'PAST_DUE', name='subscriptionstatus'), nullable=False),
    sa.Column('interval', sa.Enum('MONTHLY', 'QUARTERLY', 'ANNUALLY', name='subscriptioninterval'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('payment_gateway_sub_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['digital_asset.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_status'))

    op.drop_table('subscription')
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_transaction_token'))

    op.drop_table('purchase')
    op.drop_table('comment')
    op.drop_table('asset_file')
    with op.batch_alter_table('digital_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_digital_asset_slug'))
        batch_op.drop_index(batch_op.f('ix_digital_asset_is_published'))

    op.drop_table('digital_asset')
    with op.batch_alter_table('ambassador', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ambassador_affiliate_code'))

    op.drop_table('ambassador')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_whatsapp_number'))

    op.drop_table('customer')
    op.drop_table('creator')
    # ### end Alembic commands ###
